spring.application.name=Backend

# ----------------------------------------
# 1. C?u hình cho DB Chính (TechZoneDB)
# ----------------------------------------
spring.datasource.techzone.jdbc-url=jdbc:sqlserver://localhost:1433;database=TechZoneDB;encrypt=false
spring.datasource.techzone.username=sa
spring.datasource.techzone.password=123
spring.datasource.techzone.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ----------------------------------------
# 2. C?u hình cho DB Chat (Chat_AI)
# ----------------------------------------
spring.datasource.chatai.jdbc-url=jdbc:sqlserver://localhost:1433;database=Chat_AI;encrypt=false
spring.datasource.chatai.username=sa
spring.datasource.chatai.password=123
spring.datasource.chatai.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ----------------------------------------
# C?u hình Hibernate chung
# ----------------------------------------
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khoapdts01227@fpt.edu.vn
spring.mail.password=xxsdswzheoqtoixb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ----------------------------------------
# C?u hình Google Gemini AI
# ----------------------------------------
gemini.api.key=AIzaSyDTGEShomTyHKmIkHvPs0Zvzmz3x57v_LY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB