name: TechZoneStore CI/CD

# 1. Sự kiện kích hoạt
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 2a. Job build Backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cài đặt môi trường Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Bạn có thể đổi nếu dùng bản Java khác
          distribution: 'temurin'
          cache: maven # Giúp tăng tốc build ở các lần sau

      - name: Build Backend với Maven
        working-directory: ./Backend # Di chuyển vào thư mục Backend
        run: mvn clean package -DskipTests # Đóng gói (Tạm thời bỏ qua test để build nhanh, nếu có viết Unit Test thì xóa -DskipTests)

  # 2b. Job build Frontend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './Frontend/package-lock.json'

      - name: Cài đặt thư viện Frontend
        working-directory: ./Frontend # Di chuyển vào thư mục Frontend
        run: npm install

      - name: Build Frontend (Vite)
        working-directory: ./Frontend
        run: npm run build